### ISSUE TITLE
Switch to Alert not able to take ScreenShot on Chrome and throw exception 

### ISSUE THREAD

**Issue by Doringber** [savanna-projects/rhino-agent#36]
## Excption 
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not find file 'C:\Users\dori\Documents\automation-env\Rhino 2020-07-23\images\20200909072303726-7-Click.png'.
File name: 'C:\Users\dori\Documents\automation-env\Rhino 2020-07-23\images\20200909072303726-7-Click.png'
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at Automation.Kdd.Reporting.Reporter.CreateScreenshotsFolder(TestCase testCase, String inFolder)
   at Automation.Kdd.Reporting.Reporter.CreateScreenshotsFolder(TestRun testRun, String inFolder)
   at Automation.Kdd.Reporting.Reporter.Generate(TestRun testRun)
   at Automation.Kdd.Bridge.Connector.OnReporting()
   at Automation.Kdd.Bridge.Connector.Reporting()
   at Automation.Kdd.Bridge.Connector.Execute()
   at Automation.Extensions.Kdd.ConfigurationExtensions.Execute(KddConfiguration configuration, IEnumerable`1 types)
   at Automation.Kdd.Agent.Controllers.RhinoController.ExecuteConfigurations(IEnumerable`1 configurations)
   at Automation.Kdd.Agent.Controllers.RhinoController.ExecuteByConfiguration()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

## Steps that case for this
```
7. click on {ctl00_ContentPlaceHolder1_grvAccountsList_ctl03_hlkEdit} using {id}
8. switch to alert {accept}
```

Step 7 will display as fail and on step 8 will not able to take a screenshot

**Comment by gravity-api** [comment]
resolved
