### ISSUE TITLE
Error 500 when sending automation with invalid Plugin name

### ISSUE THREAD

**Issue by gravity-api** [savanna-projects/rhino-agent#54]
```
Rhino.Agent Warning: 0 : plugin [] was not found. please make sure you have provided a valid name
Rhino.Agent Error: 0 : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> OpenQA.Selenium.WebDriverTimeoutException: Timed out after 15 seconds: Element(s) were not found within 15sec. Consider changing element searching criteria or extending the timeout.
---> OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#acceptBT"}
  (Session info: chrome=78.0.3904.87)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Common.ExpectedConditions.<>c__DisplayClass1_0.<ElementExists>b__0(IWebDriver driver)
   at OpenQA.Selenium.Extensions.WebDriverExtensions.<>c__DisplayClass19_0.<DoGetElement>b__0(IWebDriver d)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   --- End of inner exception stack trace ---

```

**Comment by gravity-api** [comment]
Not  reproduceable
